# Generated by Django 3.0.8 on 2020-07-09 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='firstname', max_length=100)),
                ('lastname', models.CharField(default='lastname', max_length=100)),
                ('contact', models.CharField(default='contact', max_length=20)),
                ('city', models.CharField(default='city', max_length=100)),
                ('region', models.CharField(default='region', max_length=100)),
                ('country', models.CharField(default='country', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('loc_lat', models.FloatField(verbose_name='Latitude')),
                ('loc_long', models.FloatField(verbose_name='Longitude')),
                ('contact', models.CharField(max_length=20)),
                ('website', models.URLField(default='www.google.com')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
