# Generated by Django 3.0.8 on 2020-07-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pharmacist',
            field=models.BooleanField(default=False),
        ),
    ]
